spring:
  application:
    name: iticket
  datasource:
    url: jdbc:postgresql://localhost:5432/iticket_db
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
  mail:
    host: smtp.gmail.com
    port: 587
    username: qadirzadaaytac@gmail.com
    password: "aonn bqte mldb zbcc"
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
iyzico:
  api-key: sandbox-oAr3fk6dpzUDMYCjS4S0aoLhlnhXzPPL
  secret-key: sandbox-mrvK4r9O7jdQyonzVysdX1BB2oixl6A5
  base-url: https://sandbox-api.iyzipay.com
minio:
  url: http://localhost:9000
  access-key: aytac
  secret-key: P@55w0rd!
  bucket: iticket
